.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.TH man 1 "10 May 2016" "1.2" "Qtesseract5 man page"

.SH NAME
qtesseract5 \- convert IDX/SUB file in SRT file.

.SH SYNOPSIS
.B qtesseract5
.RI [ options ]
source destination

.SH DESCRIPTION
\fBQtesseract5\fP is a software who converts the IDX/SUB file in SRT (text) file. For that works, it use
.I subp2pgm
(export the images files from SUB file),
.I Tesseract
(for read their files) ans
.I subptools
(to create a SRT file).

.SH INFOS
It's possible to pause or stop by creating a file named "Pause" or "Stop" in its temp folder (for external sofwtare).

.SH OPTIONS
.IP \fB\-q,\ -\-quiet\fP
Don't reply informations.
.IP \fB\-p,\ -\-pourcentage\fP
Don't reply progression in no gui mode.
.IP \fB\-g,\ \-\-no\-gui\fP
Hide the progress dialog.
.IP \fB\-l,\ \-\-language\fP
Language to use by Tesseract for convert the images.
.IP \fB\-c,\ \-\-cpu\fP
Number of cpu to use, by default is the max.
.IP \fB\-o,\ \-\-open\fP
Automatically open the SRT file created.

.SH NOTES
This is the first release of my software.
.PP
Contact me if you have questions.
.PP
https://forum.ubuntu-fr.org/viewtopic.php?pid=21507283

.SH AUTHOR
Terence Belleguic <hizo@free.fr>
The icon has been created by me from the icons of the Oxygen Theme: https://techbase.kde.org/Projects/Oxygen